package com.tino1b2be.dtmf.io.wav;

// Feature: dtmf-io, Property 13: WAV round-trip preserves samples

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.List;

import com.tino1b2be.dtmf.DtmfConfig;
import com.tino1b2be.dtmf.DtmfGenerator;
import com.tino1b2be.dtmf.DtmfTone;
import com.tino1b2be.dtmf.io.AudioSource;
import com.tino1b2be.dtmf.io.DtmfFileDecoder;

import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;

/**
 * Property-based test for WAV round-trip accuracy (Task 6.10).
 *
 * <p><strong>Property 13: WAV round-trip preserves samples within
 * quantization tolerance.</strong> <strong>Validates: Requirements
 * 13.1, 13.2, 13.3, 9.7, 9.8.</strong>
 *
 * <p>The property has three independent arms, one per acceptance
 * criterion inside Requirement 13:
 *
 * <ol>
 *   <li><strong>PCM16 mono round-trip (Req 13.1).</strong> For a
 *       random {@code double[]} in {@code [-1.0, 1.0]} at any of the
 *       four Supported_Sample_Rates {@code {8000, 16000, 44100,
 *       48000}}, encoding with the test-only
 *       {@link WavEncoder#encodePcm16Mono(double[], int)} and decoding
 *       through {@link WavAudioSourceProvider} preserves every sample
 *       to within the PCM16 quantisation tolerance
 *       {@code 1 / 32768.0 + 1e-12}. This pins the decode normalisation
 *       contract in Requirement 9.14 (signed 16-bit integers divided by
 *       {@code 2^15}) together with the round-trip tolerance promised
 *       by Req 13.1. The trailing {@code 1e-12} absorbs floating-point
 *       rounding error in the quantise/dequantise arithmetic.</li>
 *   <li><strong>PCM_Float 32-bit mono round-trip (Req 13.2).</strong>
 *       For the same inputs, encoding with
 *       {@link WavEncoder#encodePcmFloatMono(double[], int)} and
 *       decoding through {@link WavAudioSourceProvider} is bit-exact to
 *       the widening cast of the intermediate {@code float[]} that the
 *       encoder wrote to disk. The encoder narrows each {@code double}
 *       to a {@code float} via the JLS narrowing conversion, then
 *       writes the {@code float} bits; the decoder reads those bits
 *       back and widens them to {@code double} without scaling. Both
 *       the widening and the narrowing are lossless round-trips on the
 *       narrowed value, so the decoded sample equals
 *       {@code (double) (float) input} exactly (no epsilon
 *       needed).</li>
 *   <li><strong>DTMF sequence round-trip through
 *       {@link DtmfFileDecoder} (Req 13.3).</strong> For random DTMF
 *       key sequences generated by
 *       {@link DtmfGenerator#generate(String, DtmfConfig)} at any of
 *       the four sample rates, encoding as PCM16 mono and decoding via
 *       {@link DtmfFileDecoder#decode(java.io.InputStream, String,
 *       DtmfConfig)} with {@link DtmfConfig#forTelephony()} yields a
 *       {@link List} of {@link DtmfTone} whose {@code key} values, in
 *       order, equal the original sequence. This exercises the full
 *       provider → WAV parser → sample decode → analysis-block →
 *       Goertzel detection path on the same bytes the first two arms
 *       produced, anchoring Req 13.3 against the entire I/O stack
 *       rather than just the sample-level codec. {@code forTelephony()}
 *       hard-codes {@code 8000 Hz}; {@code DtmfFileDecoder}
 *       auto-resolves by rebuilding the config with the source's rate
 *       (Req 17.1, 17.2), which is the exact auto-resolve behaviour
 *       this arm is meant to anchor alongside the round-trip
 *       claim.</li>
 * </ol>
 *
 * <h2>Why three {@code @Property} methods instead of one</h2>
 *
 * Each arm has a different natural input shape (the first two vary a
 * {@code double[]}, the third varies a DTMF key sequence) and a
 * different cost profile (the DTMF arm is considerably more expensive
 * because it runs the full Goertzel detector end-to-end). Splitting
 * them also lets jqwik shrink a counter-example inside a single arm
 * without dragging the other arms' generators into the shrinker, which
 * keeps failure diagnostics local to the arm that failed. All three
 * still fall under Property 13 because they share a single invariant
 * (Requirements 13.1, 13.2, 13.3), and Req 13 explicitly enumerates
 * the three arms as separate acceptance criteria.
 *
 * <h2>Generator bounds</h2>
 *
 * The {@code double[]} arms use lengths in {@code [100, 16000]} to
 * hit a range from "much shorter than a typical analysis block" to
 * "two full seconds at 8 kHz, one third of a second at 48 kHz" —
 * enough audio that the WAV parser's data-chunk reader iterates through
 * its internal loop multiple times, while staying small enough that
 * 100 iterations of the property run in a few seconds total. The DTMF
 * arm uses sequences of 3..8 keys, which is representative of typical
 * telephony input and keeps the longest generated audio at around
 * 48000 Hz * (8 keys * 80 ms tone + 7 gaps * 40 ms) ≈ 3.1 seconds.
 * The DTMF arm uses {@code tries = 20} because each iteration does a
 * full Goertzel pass; at tries = 100 the DTMF arm dominates the test
 * runtime of this file by an order of magnitude without improving
 * coverage much.
 *
 * <h2>Tolerances</h2>
 *
 * The PCM16 tolerance {@code 1 / 32768.0 + 1e-12} is the exact bound
 * required by Req 13.1. The PCM_Float arm asserts bit-exact equality
 * to {@code (double) (float) input}; no epsilon is used because the
 * float round-trip is lossless on the narrowed value.
 */
class WavRoundTripPropertyTest {

    /** DTMF keys accepted by {@link DtmfGenerator}. */
    private static final String DTMF_ALPHABET = "0123456789ABCD*#";

    /** PCM16 round-trip tolerance from Req 13.1. */
    private static final double PCM16_TOLERANCE = 1.0 / 32768.0 + 1e-12;

    // ------------------------------------------------------------------
    // Arm 1: PCM16 mono round-trip (Req 13.1, Req 9.14)
    // ------------------------------------------------------------------

    /**
     * For any {@code double[]} of samples in {@code [-1.0, 1.0]} at
     * any Supported_Sample_Rate, encode → decode through
     * {@link WavAudioSourceProvider} preserves every sample to within
     * the PCM16 quantisation tolerance (Req 13.1).
     *
     * <p>Uses the {@code open(InputStream, String)} overload so the
     * test exercises the stream-backed {@link WavAudioSource} path —
     * the same path the {@code DtmfFileDecoder.decode(InputStream, …)}
     * overload used in arm 3 relies on. The encoded bytes are wrapped
     * in a {@link ByteArrayInputStream} (markable, so the
     * {@code canOpen} contract's {@code mark}/{@code reset} path is
     * also exercised end-to-end).
     */
    @Property(tries = 100)
    void pcm16MonoRoundTripWithinQuantizationTolerance(
            @ForAll("supportedSampleRates") int sampleRate,
            @ForAll("normalizedSamples") double[] samples)
            throws IOException {

        byte[] wav = WavEncoder.encodePcm16Mono(samples, sampleRate);
        double[] decoded = readAllSamples(wav, samples.length);

        assertEquals(samples.length, decoded.length,
                "Decoded sample count must match input sample count");

        for (int i = 0; i < samples.length; i++) {
            double error = Math.abs(decoded[i] - samples[i]);
            final int idx = i;
            assertTrue(error <= PCM16_TOLERANCE,
                    () -> "PCM16 round-trip per-sample error exceeds "
                            + PCM16_TOLERANCE + " at index " + idx
                            + ": input=" + samples[idx]
                            + ", decoded=" + decoded[idx]
                            + ", error=" + error
                            + " (sampleRate=" + sampleRate + ")");
        }
    }

    // ------------------------------------------------------------------
    // Arm 2: PCM_Float 32-bit mono round-trip (Req 13.2, Req 9.8)
    // ------------------------------------------------------------------

    /**
     * For any {@code double[]} of samples in {@code [-1.0, 1.0]} at
     * any Supported_Sample_Rate, encode via
     * {@link WavEncoder#encodePcmFloatMono(double[], int)} and decode
     * through {@link WavAudioSourceProvider} yields a {@code double[]}
     * bit-exact to the widening cast of the intermediate
     * {@code float[]} that the encoder wrote to disk (Req 13.2).
     *
     * <p>The encoder emits each sample as
     * {@code Float.floatToIntBits((float) sample)}; the decoder reads
     * the same bits back and widens to {@code double}. Both conversions
     * are exact on the narrowed value, so equality is asserted via
     * {@link Double#doubleToLongBits(double)} — the sharpest possible
     * check, which would catch even a {@code +0.0 / -0.0} drift or an
     * accidental scaling. A plain {@code ==} comparison would fail on
     * {@code NaN} but the input range {@code [-1.0, 1.0]} excludes
     * {@code NaN} by construction.
     */
    @Property(tries = 100)
    void pcmFloat32MonoRoundTripIsBitExactToWideningCast(
            @ForAll("supportedSampleRates") int sampleRate,
            @ForAll("normalizedSamples") double[] samples)
            throws IOException {

        byte[] wav = WavEncoder.encodePcmFloatMono(samples, sampleRate);
        double[] decoded = readAllSamples(wav, samples.length);

        assertEquals(samples.length, decoded.length,
                "Decoded sample count must match input sample count");

        for (int i = 0; i < samples.length; i++) {
            // The encoder wrote (float) samples[i]; the decoder widens
            // those same bits to double. The decoded value must equal
            // the widening cast of the narrowed input exactly.
            double expected = (double) (float) samples[i];
            double actual = decoded[i];
            final int idx = i;
            assertEquals(
                    Double.doubleToLongBits(expected),
                    Double.doubleToLongBits(actual),
                    () -> "PCM_Float 32-bit round-trip not bit-exact to"
                            + " (double)(float)input at index " + idx
                            + ": input=" + samples[idx]
                            + ", expected=" + expected
                            + ", decoded=" + actual
                            + " (sampleRate=" + sampleRate + ")");
        }
    }

    // ------------------------------------------------------------------
    // Arm 3: DTMF sequence round-trip (Req 13.3)
    // ------------------------------------------------------------------

    /**
     * For any DTMF key sequence generated by
     * {@link DtmfGenerator#generate(String, DtmfConfig)} at any
     * Supported_Sample_Rate, encoding to PCM16 mono WAV and decoding
     * through {@link DtmfFileDecoder#decode(java.io.InputStream,
     * String, DtmfConfig)} with {@link DtmfConfig#forTelephony()}
     * yields a tone list whose {@code key}s, in order, equal the input
     * sequence (Req 13.3).
     *
     * <p>{@code forTelephony()} fixes the decode config at {@code 8000
     * Hz}; {@code DtmfFileDecoder} auto-resolves to the source's rate
     * by rebuilding the config with the source's sample rate (Req 17.1,
     * 17.2). That is the same auto-resolve path covered by Property 10;
     * here we exercise it as a side-effect of the round-trip rather
     * than as the primary invariant.
     *
     * <p>Uses {@code tries = 20} because each iteration runs the full
     * Goertzel detector over up to ~3 seconds of synthesized audio,
     * which is an order of magnitude more expensive than the per-sample
     * arms above. Twenty iterations still exercises all four sample
     * rates and a wide spread of sequences; the DTMF synthesis +
     * detection pipeline itself is already independently property-
     * tested in {@code dtmf-core}, so this arm's role is anchoring the
     * I/O round-trip, not re-validating the detector.
     */
    @Property(tries = 20)
    void dtmfSequenceRoundTripThroughDtmfFileDecoder(
            @ForAll("supportedSampleRates") int sampleRate,
            @ForAll("dtmfSequences") String sequence) throws IOException {

        // Generate the synthesized audio at the source's sample rate.
        // We use forTelephony()'s durations (40 ms tone, 40 ms gap)
        // regardless of rate by rebuilding the standard config via the
        // advanced builder; forTelephony() itself hard-codes 8 kHz and
        // would reject other rates at the builder. Using an advanced-
        // built config for *generation* keeps the generator and decoder
        // talking about the same (tone duration, gap duration) pair.
        DtmfConfig genConfig = DtmfConfig.advanced()
                .sampleRate(sampleRate)
                .minimumToneDuration(DtmfConfig.forTelephony().minimumToneDuration())
                .minimumGapDuration(DtmfConfig.forTelephony().minimumGapDuration())
                .build();
        double[] samples = DtmfGenerator.generate(sequence, genConfig);

        // Encode as PCM16 mono at the chosen rate and decode through
        // DtmfFileDecoder. forTelephony() is pinned to 8 kHz; the
        // decoder auto-resolves to the source's rate (Req 17.1).
        byte[] wav = WavEncoder.encodePcm16Mono(samples, sampleRate);
        List<DtmfTone> tones;
        try (ByteArrayInputStream in = new ByteArrayInputStream(wav)) {
            tones = DtmfFileDecoder.decode(in, "test.wav", DtmfConfig.forTelephony());
        }

        assertNotNull(tones,
                "DtmfFileDecoder.decode must return a non-null tone list");

        // Extract the decoded key sequence and compare to the input.
        // The round-trip invariant is exact equality on the key string
        // (Req 13.3). Any mismatch — a missed tone, an extra tone, a
        // misclassified key — fails the property.
        StringBuilder decodedKeys = new StringBuilder(tones.size());
        for (DtmfTone tone : tones) {
            decodedKeys.append(tone.key());
        }
        assertEquals(sequence, decodedKeys.toString(),
                () -> "DTMF key sequence round-trip failed at sampleRate="
                        + sampleRate + ": input='" + sequence
                        + "', decoded='" + decodedKeys + "' ("
                        + tones.size() + " tones)");
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    /**
     * Open the encoded WAV bytes via {@link WavAudioSourceProvider},
     * read every sample into a fresh {@code double[]}, and return it.
     *
     * <p>Drains the {@link AudioSource} in fixed-size chunks so the
     * read loop itself is exercised (rather than a single
     * full-buffer read). The returned array is sized to exactly
     * {@code expectedLength}; if the source returns fewer or more
     * samples the caller's assertion on {@code decoded.length} will
     * catch it.
     */
    private static double[] readAllSamples(byte[] wavBytes, int expectedLength)
            throws IOException {
        WavAudioSourceProvider provider = new WavAudioSourceProvider();
        try (ByteArrayInputStream in = new ByteArrayInputStream(wavBytes);
             AudioSource source = provider.open(in, "test.wav")) {

            // Source is mono PCM16 (or PCM_Float); one sample per frame.
            // Allocate exactly the expected capacity; an over- or
            // under-read shows up as a mismatch in decoded.length.
            double[] out = new double[expectedLength];
            int written = 0;
            while (written < expectedLength) {
                int framesToRequest = expectedLength - written;
                int framesRead = source.read(out, written, framesToRequest);
                if (framesRead < 0) {
                    break;
                }
                // read(...) is allowed to return 0 on a retryable read;
                // the WAV source in practice never does, but treat it
                // as forward progress only when n > 0.
                if (framesRead == 0) {
                    // Defensive: avoid an infinite loop on a pathological
                    // source that returned 0 repeatedly without hitting
                    // end-of-stream.
                    break;
                }
                written += framesRead;
            }

            // If the source yielded fewer samples than expected, trim
            // so the caller's assertion on decoded.length reports
            // accurately.
            if (written != expectedLength) {
                double[] trimmed = new double[written];
                System.arraycopy(out, 0, trimmed, 0, written);
                return trimmed;
            }
            return out;
        }
    }

    // ------------------------------------------------------------------
    // Generators
    // ------------------------------------------------------------------

    /**
     * Random {@code double[]} samples of length {@code [100, 16_000]},
     * each element uniformly drawn from {@code [-1.0, 1.0]} with a
     * scale that lets jqwik cover sub-quantum values freely. The bound
     * 16 000 samples lines up with the {@code @Size} used elsewhere in
     * the test suite ({@code DtmfDecoderArrayRetentionPropertyTest},
     * {@code StereoDownmixEqualsMonoPropertyTest}) and keeps the
     * longest PCM16 round-trip at 2 seconds of mono audio at 8 kHz /
     * 0.33 seconds at 48 kHz — well under the per-try budget.
     *
     * <p>{@code .ofScale(9)} matches the jqwik pattern already in use
     * in {@code DtmfDecoderArrayRetentionPropertyTest}: default
     * scale-2 {@code double} arbitraries restrict to two decimal
     * digits, which severely narrows the generator's reach; scale 9
     * admits values like {@code 0.123456789} that exercise sub-quantum
     * rounding paths in the PCM16 quantiser.
     */
    @Provide
    Arbitrary<double[]> normalizedSamples() {
        Arbitrary<Double> sample = Arbitraries.doubles()
                .between(-1.0, 1.0).ofScale(9);
        return sample.array(double[].class).ofMinSize(100).ofMaxSize(16_000);
    }

    /**
     * The four Supported_Sample_Rates from Requirement 13:
     * {@code {8000, 16000, 44100, 48000}} Hz.
     */
    @Provide
    Arbitrary<Integer> supportedSampleRates() {
        return Arbitraries.of(8_000, 16_000, 44_100, 48_000);
    }

    /**
     * Random DTMF key sequences of length 3..8 over the 16-character
     * alphabet accepted by {@link DtmfGenerator} (digits {@code 0-9},
     * letters {@code A-D}, {@code *}, {@code #}).
     *
     * <p>Length 3..8 is the representative telephony range; 3 is the
     * lower end of "worth testing as a sequence" and 8 is the upper
     * end where encode/decode at 48 kHz stays comfortably under a few
     * seconds of audio per try.
     */
    @Provide
    Arbitrary<String> dtmfSequences() {
        Arbitrary<Character> keys = Arbitraries.of(toCharacterArray(DTMF_ALPHABET));
        return keys.list().ofMinSize(3).ofMaxSize(8)
                .map(list -> {
                    StringBuilder sb = new StringBuilder(list.size());
                    for (Character c : list) {
                        sb.append(c.charValue());
                    }
                    return sb.toString();
                });
    }

    /**
     * Convert a {@link String} to a {@link Character} array so
     * {@link Arbitraries#of(Object[])} can enumerate its characters
     * as draw targets. {@code Arbitraries.of(String)} does not exist;
     * {@code Arbitraries.chars()} is broader than we want (full Unicode
     * code-point range).
     */
    private static Character[] toCharacterArray(String s) {
        Character[] chars = new Character[s.length()];
        for (int i = 0; i < s.length(); i++) {
            chars[i] = s.charAt(i);
        }
        return chars;
    }
}
