package com.tino1b2be.dtmf.internal;

// Feature: dtmf-v2-foundation, Property 6: Sample-format normalization

import static org.junit.jupiter.api.Assertions.assertEquals;

import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.constraints.Size;

/**
 * Property-based tests for {@link SampleConverter}.
 *
 * <p><strong>Property 6: Sample-format normalization.</strong>
 * <strong>Validates: Requirements 4.5, 4.6, 4.7.</strong>
 *
 * <p>Three properties assert the pointwise conversion identities from
 * {@code design.md}:
 *
 * <ul>
 *   <li>{@code SampleConverter.fromShort(s)[i] == s[i] / 32768.0} for all
 *       {@code i}.</li>
 *   <li>{@code SampleConverter.fromFloat(f)[i] == (double) f[i]} for all
 *       {@code i} — exact widening, {@code NaN} and {@code ±Infinity}
 *       preserved bit-for-bit.</li>
 *   <li>{@code SampleConverter.fromInt(n)[i] == n[i] / 2147483648.0} for all
 *       {@code i}.</li>
 * </ul>
 *
 * <p>Equality is asserted bit-exactly: the conversion formulas are simple
 * divisions by exact powers of two (for the integer variants) and a direct
 * widening cast (for the float variant). No fuzz is warranted — if the
 * assertion trips on even one input, the implementation has drifted from
 * the spec.
 *
 * <p>For the {@code float} property we use {@code Double.doubleToRawLongBits}
 * equality so that a {@code NaN} generated by jqwik compares equal to itself
 * (regular {@code ==} on {@code NaN} always returns {@code false}).
 */
class SampleConverterPropertyTest {

    @Property(tries = 100)
    void fromShortDividesBy32768Exactly(
            @ForAll @Size(max = 1024) short[] input) {

        double[] output = SampleConverter.fromShort(input);

        assertEquals(input.length, output.length);
        for (int i = 0; i < input.length; i++) {
            // Divisor is exactly 2^15 = 32768, representable exactly in double.
            // The per-sample division is therefore reproducible bit-for-bit.
            assertEquals(
                    input[i] / 32768.0,
                    output[i],
                    "index " + i + " input=" + input[i]);
        }
    }

    @Property(tries = 100)
    void fromFloatIsExactWidening(
            @ForAll @Size(max = 1024) float[] input) {

        double[] output = SampleConverter.fromFloat(input);

        assertEquals(input.length, output.length);
        for (int i = 0; i < input.length; i++) {
            // Compare raw bit patterns so NaN compares equal to the widened
            // NaN and ±Infinity compare as themselves. Widening a float to
            // double is exact: every finite float is representable as a
            // double, and special values are preserved.
            long expectedBits = Double.doubleToRawLongBits((double) input[i]);
            long actualBits = Double.doubleToRawLongBits(output[i]);
            assertEquals(
                    expectedBits,
                    actualBits,
                    "index " + i + " input=" + input[i]);
        }
    }

    @Property(tries = 100)
    void fromIntDividesBy2Pow31Exactly(
            @ForAll @Size(max = 1024) int[] input) {

        double[] output = SampleConverter.fromInt(input);

        assertEquals(input.length, output.length);
        for (int i = 0; i < input.length; i++) {
            // Divisor is exactly 2^31 = 2147483648, representable exactly in
            // double. Integer.MIN_VALUE / 2^31 == -1.0 exactly (confirms the
            // intended symmetry with the short-variant divisor choice).
            assertEquals(
                    input[i] / 2147483648.0,
                    output[i],
                    "index " + i + " input=" + input[i]);
        }
    }
}
